"""empty message

Revision ID: 1832d430032f
Revises: 69e33908073e
Create Date: 2023-09-18 00:25:57.018696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1832d430032f'
down_revision = '69e33908073e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flight_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.drop_column('flight_date')

    # ### end Alembic commands ###
