"""empty message

Revision ID: 41b880efc156
Revises: a1f250facca8
Create Date: 2023-09-23 14:33:18.810169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b880efc156'
down_revision = 'a1f250facca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('payments_ibfk_1', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_foreign_key('payments_ibfk_1', 'bookings', ['booking_id'], ['booking_id'])

    # ### end Alembic commands ###
