"""empty message

Revision ID: 6a0458260e9b
Revises: 1431f0c21354
Create Date: 2023-09-25 08:10:36.600076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a0458260e9b'
down_revision = '1431f0c21354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('bookings_ibfk_2', type_='foreignkey')
        batch_op.drop_column('payment_amount')
        batch_op.drop_column('seat_type_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seat_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('payment_amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('bookings_ibfk_2', 'seat_types', ['seat_type_id'], ['seat_type_id'])

    # ### end Alembic commands ###
