"""empty message

Revision ID: 84f93ba338b2
Revises: cc72753b57ac
Create Date: 2023-09-18 00:04:39.924418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84f93ba338b2'
down_revision = 'cc72753b57ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('booking_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_date', mysql.DATETIME(), nullable=False))

    # ### end Alembic commands ###
