"""empty message

Revision ID: a1f250facca8
Revises: 375b41c85e33
Create Date: 2023-09-21 10:01:35.301448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1f250facca8'
down_revision = '375b41c85e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cancel_booking')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancel_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paymentmethod', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('paymentmethod')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('cancel_date')

    op.create_table('cancel_booking',
    sa.Column('cancel_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('booking_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('cancel_date', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name='cancel_booking_ibfk_1'),
    sa.PrimaryKeyConstraint('cancel_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
