"""empty message

Revision ID: b2d2c42fe413
Revises: 
Create Date: 2023-09-17 15:27:16.492626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2d2c42fe413'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Airlines',
    sa.Column('airlineID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('airline_name', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('airlineID')
    )
    op.create_table('City',
    sa.Column('cityID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_name', sa.String(length=60), nullable=False),
    sa.Column('city_code', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('cityID')
    )
    op.create_table('SeatType',
    sa.Column('seatTypeID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seat_type_name', sa.String(length=25), nullable=False),
    sa.Column('seat_type_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('seatTypeID')
    )
    op.create_table('User',
    sa.Column('userID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Route',
    sa.Column('routeID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_from', sa.Integer(), nullable=False),
    sa.Column('route_to', sa.Integer(), nullable=False),
    sa.Column('Duration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_from'], ['City.cityID'], ),
    sa.ForeignKeyConstraint(['route_to'], ['City.cityID'], ),
    sa.PrimaryKeyConstraint('routeID')
    )
    op.create_table('Flight',
    sa.Column('flightID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flight_number', sa.String(length=20), nullable=False),
    sa.Column('RouteID', sa.Integer(), nullable=False),
    sa.Column('flight_price', sa.Integer(), nullable=False),
    sa.Column('AirlineID', sa.Integer(), nullable=False),
    sa.Column('SeatTypeID', sa.Integer(), nullable=False),
    sa.Column('Seat', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['AirlineID'], ['Airlines.airlineID'], ),
    sa.ForeignKeyConstraint(['RouteID'], ['Route.routeID'], ),
    sa.ForeignKeyConstraint(['SeatTypeID'], ['SeatType.seatTypeID'], ),
    sa.PrimaryKeyConstraint('flightID')
    )
    op.create_table('Booking',
    sa.Column('bookingID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('flightID', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.DateTime(), nullable=False),
    sa.Column('booking_status', sa.String(length=20), nullable=False),
    sa.Column('seatTypeID', sa.Integer(), nullable=False),
    sa.Column('payment_amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flightID'], ['Flight.flightID'], ),
    sa.ForeignKeyConstraint(['seatTypeID'], ['SeatType.seatTypeID'], ),
    sa.ForeignKeyConstraint(['userID'], ['User.userID'], ),
    sa.PrimaryKeyConstraint('bookingID')
    )
    op.create_table('Payment',
    sa.Column('paymentID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bookingID', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bookingID'], ['Booking.bookingID'], ),
    sa.PrimaryKeyConstraint('paymentID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Payment')
    op.drop_table('Booking')
    op.drop_table('Flight')
    op.drop_table('Route')
    op.drop_table('User')
    op.drop_table('SeatType')
    op.drop_table('City')
    op.drop_table('Airlines')
    # ### end Alembic commands ###
