"""empty message

Revision ID: cc72753b57ac
Revises: 
Create Date: 2023-09-18 00:03:48.285474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc72753b57ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('airline_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('airline_name', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('airline_id')
    )
    op.create_table('cities',
    sa.Column('city_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_name', sa.String(length=60), nullable=False),
    sa.Column('city_code', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('city_id')
    )
    op.create_table('seat_types',
    sa.Column('seat_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seat_type_name', sa.String(length=25), nullable=False),
    sa.Column('seat_type_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('seat_type_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('routes',
    sa.Column('route_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origin_city_id', sa.Integer(), nullable=False),
    sa.Column('destination_city_id', sa.Integer(), nullable=False),
    sa.Column('duration_hours', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destination_city_id'], ['cities.city_id'], ),
    sa.ForeignKeyConstraint(['origin_city_id'], ['cities.city_id'], ),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('flights',
    sa.Column('flight_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flight_number', sa.String(length=20), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('flight_price', sa.Integer(), nullable=False),
    sa.Column('airline_id', sa.Integer(), nullable=False),
    sa.Column('seat_type_id', sa.Integer(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['airline_id'], ['airlines.airline_id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.ForeignKeyConstraint(['seat_type_id'], ['seat_types.seat_type_id'], ),
    sa.PrimaryKeyConstraint('flight_id')
    )
    op.create_table('bookings',
    sa.Column('booking_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.DateTime(), nullable=False),
    sa.Column('booking_status', sa.String(length=20), nullable=False),
    sa.Column('seat_type_id', sa.Integer(), nullable=False),
    sa.Column('payment_amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.flight_id'], ),
    sa.ForeignKeyConstraint(['seat_type_id'], ['seat_types.seat_type_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('bookings')
    op.drop_table('flights')
    op.drop_table('routes')
    op.drop_table('users')
    op.drop_table('seat_types')
    op.drop_table('cities')
    op.drop_table('airlines')
    # ### end Alembic commands ###
