"""empty message

Revision ID: eb38ff4ae370
Revises: 4f3eb36b2545
Create Date: 2023-09-25 08:20:30.042136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb38ff4ae370'
down_revision = '4f3eb36b2545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refund_payment', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'payments', ['payment_id'], ['payment_id'])

    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'cities', ['destination_city_id'], ['city_id'])
        batch_op.create_foreign_key(None, 'cities', ['origin_city_id'], ['city_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('refund_payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
