"""empty message

Revision ID: efb23416bd73
Revises: 86c9bf43c391
Create Date: 2023-09-23 15:39:46.323157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb23416bd73'
down_revision = '86c9bf43c391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refund_payment', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['payment_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refund_payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
