"""empty message

Revision ID: fa11032d942f
Revises: 
Create Date: 2023-09-23 18:08:45.625565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa11032d942f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refund_payment',
    sa.Column('refund_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('refund_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id'], ),
    sa.PrimaryKeyConstraint('refund_id'),
    sa.UniqueConstraint('payment_id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancel_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.alter_column('flight_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paymentmethod', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['booking_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('paymentmethod')

    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.alter_column('flight_date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('cancel_date')

    op.drop_table('refund_payment')
    # ### end Alembic commands ###
